name: Deploy .NET App to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish app
        run: dotnet publish ./src/Shortify.Api/Shortify.Api.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: shortify
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish
